Repository thoth-station/solver, pull requests merged in 2018-11, with the labels that each got.

#131 Automatic update of dependency thoth-common from 0.3.16 to 0.4.0
  Pipfile.lock
Labels: bot

#136 Automatic update of dependency autopep8 from 1.4.2 to 1.4.3
  Pipfile.lock
Labels: bot

#133 if error is not fatal, loglevel has been replaced with warning
  thoth/solver/python.py
Labels: size/S

#137 Automatic update of dependency thoth-common from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#138 Automatic update of dependency thoth-common from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#139 Automatic update of dependency thoth-common from 0.4.2 to 0.4.3
  Pipfile.lock
Labels: bot

#140 Automatic update of dependency thoth-common from 0.4.3 to 0.4.4
  Pipfile.lock
Labels: bot

#132 Do not print matching solved packages on new line
  thoth/solver/solvers/base.py
Labels: size/XS

#142 Automatic update of dependency thoth-common from 0.4.4 to 0.4.5
  Pipfile.lock
Labels: bot

#143 Add long description for PyPI
  setup.py
Labels: approved, size/XS

#145 Cross-index solving with hashes gathering
  thoth/solver/cli.py
  thoth/solver/python/__init__.py
  thoth/solver/python/base.py
  thoth/solver/python/python.py
  thoth/solver/python/python_solver.py
Labels: approved, size/L

#147 Introduce THOTH_SOLVER_INDEXES variable in template
  openshift/job-template.yaml
Labels: approved, size/XS

#149 Do not forget thoth-python dependency
  requirements.txt
Labels: size/XS

#148 Fix setup.py packages
  setup.py
Labels: size/XS

#150 Enable trusted hosts by default
  thoth/solver/python/python.py
Labels: size/XS

#151 Adjust solver output to be compatible with sync
  thoth/solver/python/python.py
Labels: size/M

#152 Automatic update of dependency thoth-common from 0.4.5 to 0.4.6
  Pipfile.lock
Labels: bot

#117 Adding Fedora 28 and 29
  .coafile
  .zuul.yaml
  hack/Dockerfile.fc26
  hack/Dockerfile.fc27
  hack/build.sh
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
  pyproject.toml
  thoth/solver/__init__.py
  thoth/solver/cli.py
  thoth/solver/compile.py
  thoth/solver/python/base.py
  thoth/solver/python/python.py
  thoth/solver/python/python_solver.py
Labels: size/L, size/M, size/XL
