Repository thoth-station/solver, pull requests merged in 2018-04, with the labels that each got.

#9 adding the OWNERS file
  OWNERS
Labels: approved

#11 License and license headers
  LICENSE
  setup.py
  thoth/solver/__init__.py
  thoth/solver/cli.py
  thoth/solver/compile.py
  thoth/solver/exceptions.py
  thoth/solver/python.py
  thoth/solver/solvers/__init__.py
  thoth/solver/solvers/base.py
  thoth/solver/solvers/pypi.py
Labels: approved, size/XL

#17 Mark packages that couldn't be found as unresolvable
  thoth/solver/python.py
Labels: approved, size/S

#19 Keep track of unparsed packages
  thoth/solver/python.py
Labels: approved, size/S

#18 Simplify error handling
  thoth/solver/python.py
Labels: approved, size/S

#20 added OpenShift templates
  dependencies.yml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L
