Repository thoth-station/solver, pull requests merged in 2018-09, with the labels that each got.

#82 Automatic update of dependency autopep8 from 1.3.5 to 1.4
  Pipfile.lock
Labels: bot

#84 Automatic update of dependency thoth-common from 0.2.6 to 0.2.7
  Pipfile.lock
Labels: bot

#86 Automatic update of dependency thoth-common from 0.2.7 to 0.3.0
  Pipfile.lock
Labels: bot

#87 Fix restart policy configuration
  .gitignore
  openshift/pod-template.yaml
  thoth/solver/python.py
Labels: approved, size/S, size/XS

#92 Automatic update of dependency thoth-common from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: bot

#93 Automatic update of dependency pip-tools from 2.0.2 to 3.0.0
  Pipfile.lock
Labels: bot

#94 Automatic update of dependency click from 6.7 to 7.0
  Pipfile.lock
Labels: bot

#95 Automatic update of dependency thoth-common from 0.3.1 to 0.3.2
  Pipfile.lock
Labels: bot

#96 Automatic update of dependency thoth-common from 0.3.2 to 0.3.5
  Pipfile.lock
Labels: bot

#101 Automatic update of dependency thoth-common from 0.3.5 to 0.3.6
  Pipfile.lock
Labels: bot

#100 Be more verbose about what is going on
  thoth/solver/solvers/pypi.py
Labels: approved, size/XS

#97 Update README file
  README.rst
Labels: approved, size/M
