Repository thoth-station/solver, pull requests merged in 2018-07, with the labels that each got.

#34 Automatic update of dependency pipdeptree from 0.12.1 to 0.13.0
  Pipfile.lock
Labels: approved, bot, size/S

#33 Automatic update of dependency thoth-common from 0.0.8 to 0.0.9
  Pipfile.lock
Labels: approved, bot, size/XS

#35 Automatic update of dependency thoth-analyzer from 0.0.6 to 0.0.7
  Pipfile.lock
Labels: approved, bot, size/S

#36 /usr/bin/python3 is being removed
  setup.py
Labels: approved, size/XS

#37 Automatic update of dependency thoth-common from 0.0.9 to 0.1.0
  Pipfile.lock
Labels: bot

#43 Initial dependency lock
  Pipfile.lock
Labels: bot

#46 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#47 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#48 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#49 Introduce solver pod template
  openshift/pod-template.yaml
Labels: approved

#52 Add resources needed for build
  openshift/buildConfig-template.yaml
Labels: approved

#71 Automatic update of dependency thoth-common from 0.2.1 to 0.2.2
  Pipfile.lock
Labels: bot

#72 Update requirements.txt respecting requirements in Pipfile
  requirements.txt
Labels: bot, size/S

#73 Be consistent with naming
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/pod-template.yaml
Labels: approved, size/S
