Repository thoth-station/solver, pull requests merged in 2018-10, with the labels that each got.

#105 Automatic update of dependency pipdeptree from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot

#106 Automatic update of dependency pip-tools from 3.0.0 to 3.1.0
  Pipfile.lock
Labels: bot

#104 Move from Pods to Jobs
  openshift/job-template.yaml
  openshift/pod-template.yaml
Labels: approved, size/L

#107 Automatic update of dependency thoth-common from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: bot

#108 Automatic update of dependency thoth-common from 0.3.7 to 0.3.8
  Pipfile.lock
Labels: bot

#109 Automatic update of dependency thoth-common from 0.3.8 to 0.3.9
  Pipfile.lock
Labels: bot

#111 Automatic update of dependency thoth-common from 0.3.10 to 0.3.11
  Pipfile.lock
Labels: bot

#112 removed f26 part, added sentry
  openshift/job-template.yaml
Labels: approved, size/M

#115 Automatic update of dependency thoth-analyzer from 0.0.7 to 0.1.0
  Pipfile.lock
Labels: bot

#118 Automatic update of dependency autopep8 from 1.4 to 1.4.1
  Pipfile.lock
Labels: bot

#121 Automatic update of dependency autopep8 from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: bot

#122 Automatic update of dependency thoth-common from 0.3.12 to 0.3.13
  Pipfile.lock
Labels: bot

#123 Automatic update of dependency thoth-common from 0.3.13 to 0.3.14
  Pipfile.lock
Labels: bot

#124 Fix splitting packages in requirements
  thoth/solver/cli.py
Labels: approved, size/XS

#126 Automatic update of dependency thoth-common from 0.3.15 to 0.3.16
  Pipfile.lock
Labels: bot
