Repository thoth-station/solver, pull requests merged in 2018-12, with the labels that each got.

#156 Release of version 1.1.0
  thoth/solver/__init__.py
Labels: bot, size/XS

#158 Register solver for operator handling
  openshift/job-template.yaml
Labels: size/XS

#162 Graph sync operator was renamed
  openshift/job-template.yaml
Labels: size/XS

#159 Mark solver for cleanup
  openshift/job-template.yaml
Labels: size/XS

#163 Automatic update of dependency thoth-common from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: bot

#160 Automatic update of dependency requests from 2.20.1 to 2.21.0
  Pipfile.lock
Labels: bot

#165 Automatic update of dependency pip-tools from 3.1.0 to 3.2.0
  Pipfile.lock
Labels: bot

#166 Automatic update of dependency virtualenv from 16.1.0 to 16.2.0
  Pipfile.lock
Labels: bot
