Repository thoth-station/solver, pull requests merged in 2018-08, with the labels that each got.

#74 State all solvers and template parameters
  openshift/pod-template.yaml
Labels: approved, size/M

#75 Remove Travis CI completely
  .travis.yml
Labels: approved, size/S

#76 Increase memory for builds of f26 solver
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#78 Automatic update of dependency thoth-common from 0.2.2 to 0.2.3
  Pipfile.lock
Labels: bot

#79 Automatic update of dependency thoth-common from 0.2.3 to 0.2.4
  Pipfile.lock
Labels: bot

#80 Automatic update of dependency thoth-common from 0.2.4 to 0.2.5
  Pipfile.lock
Labels: bot
