Repository thoth-station/solver, pull requests merged in 2019-03, with the labels that each got.

#194 Fix logical error due to which we did not resolve transitive deps locally
  thoth/solver/python/python.py
Labels: size/S, size/XS

#196 Install thoth-python, use Python3.6 in virtual env
  Pipfile
  Pipfile.lock
Labels: size/L

#197 Minor fixes in implementation
  thoth/solver/python/python.py
Labels: size/XS

#198 Automatic update of dependency pip-tools from 3.4.0 to 3.5.0
  Pipfile.lock
Labels: bot

#199 Use Sphinx for documentation
  .coafile
  .gitignore
  README.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: size/L

#200 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#202 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#203 Automatic update of dependency thoth-python from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: bot

#204 added ImageStream namespace and tag
  openshift/job-template.yaml
Labels: approved, size/M, size/S
