Repository thoth-station/solver, pull requests merged in 2019-05, with the labels that each got.

#217 Minor fix to display correct release in title of docs html
  setup.py
Labels: approved, size/XS

#218 Automatic update of dependency pip-tools from 3.6.1 to 3.7.0
  Pipfile.lock
Labels: bot

#220 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#221 Automatic update of dependency virtualenv from 16.5.0 to 16.6.0
  Pipfile.lock
Labels: bot

#222 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: bot

#223 added solver for UBI8-Py36
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
Labels: approved

#224 we need to provide a pull secret
  openshift/buildConfig-template.yaml
Labels: approved

#225 a little bit more verbosity
  thoth/solver/python/python.py
Labels: approved

#226 Retry if subgraph check API does not respond with correct status code
  thoth/solver/python/python.py
Labels: approved

#229 modify link
  README.rst
Labels: approved, size/XS
