Repository thoth-station/solver, pull requests merged in 2019-09, with the labels that each got.

#284 Automatic update of dependency virtualenv from 16.7.4 to 16.7.5
  Pipfile.lock
Labels: bot

#286 Automatic update of dependency thoth-python from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot

#288 Fix issue when fetcher kwargs are set to None
  thoth/solver/python/base.py
Labels: approved, size/XS

#290 Implicitly turn off subgraph checks if transitive will not be resolved
  thoth/solver/python/python.py
Labels: approved, size/XS

#291 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#293 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#295 Automatic update of dependency thoth-analyzer from 0.1.2 to 0.1.3
  Pipfile.lock
Labels: bot

#296 Automatic update of dependency thoth-python from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: bot

#298 Use only ubi based image in job
  openshift/job-template.yaml
Labels: approved, size/M

#300 Fix gathering of hashes for packages which have different versions on PyPI
  thoth/solver/python/python.py
Labels: size/XS

#301 Add duration to Solver
  thoth/solver/cli.py
Labels: approved, size/XS

#303 Automatic update of dependency thoth-analyzer from 0.1.3 to 0.1.4
  Pipfile.lock
Labels: bot

#302 Fix duration calculation
  thoth/solver/cli.py
Labels: approved, size/XS
