Repository thoth-station/solver, pull requests merged in 2019-02, with the labels that each got.

#178 Update year in sources
  thoth/solver/__init__.py
  thoth/solver/cli.py
  thoth/solver/compile.py
  thoth/solver/exceptions.py
  thoth/solver/python/__init__.py
  thoth/solver/python/base.py
  thoth/solver/python/python.py
  thoth/solver/python/python_solver.py
Labels: size/S

#180 Automatic update of dependency virtualenv from 16.2.0 to 16.4.0
  Pipfile.lock
Labels: bot

#181 Automatic update of dependency pip-tools from 3.2.0 to 3.3.2
  Pipfile.lock
Labels: bot

#184 Automatic update of dependency thoth-analyzer from 0.1.0 to 0.1.2
  Pipfile.lock
Labels: bot

#185 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#186 added f28, f29 solvers, relocked pipfile
  .coafile
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
Labels: approved, size/L

#187 using the correct name now
  openshift/job-template.yaml
Labels: size/XS

#189 Automatic update of dependency pip-tools from 3.3.2 to 3.4.0
  Pipfile.lock
Labels: bot

#190 Automatic update of dependency virtualenv from 16.4.0 to 16.4.1
  Pipfile.lock
Labels: bot

#191 Restart solver run if anything goes wrong
  openshift/job-template.yaml
Labels: size/XS

#192 Cleanup successful solver jobs after 2 hours
  openshift/job-template.yaml
Labels: size/XS

#193 Automatic update of dependency virtualenv from 16.4.1 to 16.4.3
  Pipfile.lock
Labels: bot
