Repository thoth-station/solver, pull requests merged in 2019-11, with the labels that each got.

#355 Lower requests for running solver jobs
  openshift/job-template.yaml
Labels: approved, size/XS

#354 Remove ttl configuration for cleanup
  openshift/job-template.yaml
Labels: approved, size/XS

#356 Aggregate information which is a list of strings
  tests/data/metadata/tensorflow.json
  tests/data/metadata/tensorflow_extracted.json
  tests/python/test_instrument.py
  thoth/solver/python/instrument.py
Labels: approved, size/M, size/S

#357 Provide information if the given package was found on the index
  thoth/solver/python/python.py
Labels: approved, size/XS

#363 Add README metadata based on the current implementation
  README.rst
Labels: approved, size/M

#358 Rewrite solver to use packaging instead of pip internals
  .gitignore
  Pipfile
  Pipfile.lock
  mypy.ini
  requirements.txt
  setup.py
  tests/base.py
  tests/python/test_instrument.py
  tests/python/test_python.py
  tests/python/test_python_solver.py
  thoth/solver/__init__.py
  thoth/solver/_typing.py
  thoth/solver/cli.py
  thoth/solver/compile.py
  thoth/solver/exceptions.py
  thoth/solver/py.typed
  thoth/solver/python/__init__.py
  thoth/solver/python/base.py
  thoth/solver/python/instrument.py
  thoth/solver/python/python.py
  thoth/solver/python/python_solver.py
Labels: approved, size/XXL

#360 Provide an option to pass pre-built virtualenvironment
  openshift/buildConfig-template.yaml
  openshift/job-template.yaml
  thoth/solver/cli.py
  thoth/solver/python/python.py
Labels: approved, size/M, size/XXL

#366 Automatic update of dependency thoth-python from 0.6.5 to 0.7.1
  Pipfile.lock
Labels: bot

#367 Release of version 1.4.0
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: bot, size/L, size/M

#369 Upgrade setuptools present in the base image on build
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#364 Update the README file to show how to run solver locally
  README.rst
Labels: approved, size/M

#370 Fix permission issues in solver runs
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#371 Fix issues with solver venv installation
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#372 build from the latest release of ubi8
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#374 introduced rhel81 solver
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved

#375 Document how to create and install solver in Thoth
  README.rst
Labels: approved, size/S

#376 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#377 f30 & f31 based solver images
  .zuul.yaml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#378 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#379 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/XS

#380 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/XS

#381 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#382 Automatic update of dependency virtualenv from 16.7.7 to 16.7.8
  Pipfile.lock
Labels: bot, size/M

#383 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#387 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#384 Propagate document id into job
  openshift/job-template.yaml
Labels: approved, size/XS

#388 Automatic update of dependency thoth-analyzer from 0.1.4 to 0.1.5
  Pipfile.lock
Labels: bot, size/M

#390 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/M

#391 Automatic update of dependency mypy from 0.740 to 0.750
  Pipfile.lock
Labels: bot, size/M

#392 Automatic update of dependency importlib-metadata from 0.23 to 1.0.0
  Pipfile.lock
Labels: bot, size/S
