Repository thoth-station/solver, pull requests merged in 2019-01, with the labels that each got.

#168 Pass solver job identifier for workload operator
  openshift/job-template.yaml
Labels: size/XS

#169 Use solver naming convention
  openshift/job-template.yaml
Labels: size/XS

#170 Fix debug message printed
  .gitignore
  thoth/solver/python/python.py
Labels: size/S, size/XS

#172 Automatic update of dependency thoth-common from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot
