Repository thoth-station/solver, pull requests merged in 2019-12, with the labels that each got.

#393 Automatic update of dependency importlib-metadata from 1.0.0 to 1.1.0
  Pipfile.lock
Labels: bot, size/S

#395 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/M

#397 Automatic update of dependency importlib-metadata from 1.1.0 to 1.1.2
  Pipfile.lock
Labels: bot, size/M

#398 Automatic update of dependency importlib-metadata from 1.1.2 to 1.2.0
  Pipfile.lock
Labels: bot, size/S

#399 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/XS

#400 Change Sphinx theme
  docs/source/conf.py
Labels: approved

#402 Automatic update of dependency thoth-analyzer from 0.1.5 to 0.1.6
  Pipfile.lock
Labels: bot, size/S

#401 Propagate information whether the given package and version is provided by index
  thoth/solver/python/python.py
Labels: approved, size/S

#404 Release of version 1.4.1
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: bot, size/L

#394 added the OpenShift Template for the Argo Workflow
  .coafile
  openshift/solve_and_sync-template.yaml
  setup.py
  thoth/solver/python/instrument.py
Labels: approved, size/L

#405 Add Google Analytics
  docs/source/_templates/layout.html
Labels: approved, size/S

#406 Point documentation to other libraries
  docs/source/index.rst
Labels: approved, size/XS

#407 Automatic update of dependency thoth-analyzer from 0.1.6 to 0.1.7
  Pipfile.lock
Labels: bot, size/M

#340 all solver jobs for production and stage cluster
  openshift/all-jobs-template.yaml
Labels: size/L

#409 Use Python 3.8 instead of Python 3.7
  openshift/all-jobs-template.yaml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/M

#408 Automatic update of dependency importlib-metadata from 1.2.0 to 1.3.0
  Pipfile.lock
Labels: bot, size/M

#410 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/S

#411 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/XS

#412 Automatic update of dependency virtualenv from 16.7.8 to 16.7.9
  Pipfile.lock
Labels: bot, size/M

#413 Automatic update of dependency mypy from 0.750 to 0.760
  Pipfile.lock
Labels: bot, size/M

#415 Automatic update of dependency mypy from 0.760 to 0.761
  Pipfile.lock
Labels: bot, size/M

#416 Solver Fedora 31 with Python 3.7
  openshift/all-jobs-template.yaml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L
