Repository thoth-station/solver, pull requests merged in 2019-10, with the labels that each got.

#294 WIP: Aggregate package metadata for markers and extras
  Pipfile
  Pipfile.lock
  thoth/solver/python/python.py
Labels: approved, size/M, size/XL

#304 Revert "WIP: Aggregate package metadata for markers and extras"
  Pipfile
  Pipfile.lock
  thoth/solver/python/python.py
Labels: size/XL

#308 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#309 Aggregate package metadata for markers and extras
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/solver/cli.py
  thoth/solver/python/instrument.py
  thoth/solver/python/python.py
Labels: size/XXL

#311 Add testsuite for new implementation
  .coafile
  .gitignore
  .zuul.yaml
  Pipfile
  Pipfile.lock
  setup.py
  tests/base.py
  tests/data/metadata/tensorflow.json
  tests/data/metadata/tensorflow_extracted.json
  tests/python/__init__.py
  tests/python/test_instrument.py
  tests/python/test_python.py
  tests/python/test_python_solver.py
  thoth/solver/python/python.py
Labels: size/XL

#313 Marker evaluation change
  README.rst
  tests/data/metadata/tensorflow_extracted.json
  tests/python/test_python.py
  thoth/solver/python/python.py
Labels: size/L

#314 Drop subgraph checks
  Pipfile
  Pipfile.lock
  README.rst
  openshift/job-template.yaml
  tests/python/test_python.py
  thoth/solver/cli.py
  thoth/solver/python/python.py
Labels: size/L

#315 Add test for parsing extra and extras
  tests/python/test_python.py
Labels: size/S

#316 Be backwards compatible with older release
  tests/data/metadata/tensorflow_extracted.json
  tests/python/test_python.py
  thoth/solver/python/python.py
Labels: approved, size/S

#317 Bump version
  thoth/solver/__init__.py
Labels: approved, size/S, size/XS

#319 Be backwards compatible with older versions of solver
  tests/data/metadata/tensorflow_extracted.json
  thoth/solver/python/python.py
Labels: approved, size/XS

#321 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#322 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#323 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.1
  Pipfile.lock
Labels: bot

#324 Automatic update of dependency thoth-python from 0.6.3 to 0.6.4
  Pipfile.lock
Labels: bot

#325 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#328 Reverse order of imports during venv instrumentation
  tests/python/test_instrument.py
  thoth/solver/python/instrument.py
  thoth/solver/python/python.py
Labels: approved, size/M

#329 Be consistent with index_url and package_version
  thoth/solver/python/python.py
Labels: approved, size/XS

#330 Automatic update of dependency pip-tools from 4.1.0 to 4.2.0
  Pipfile.lock
Labels: bot

#332 Automatic update of dependency virtualenv from 16.7.5 to 16.7.6
  Pipfile.lock
Labels: bot

#335 Automatic update of dependency thoth-python from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#336 Automatic update of dependency virtualenv from 16.7.6 to 16.7.7
  Pipfile.lock
Labels: bot

#338 Update the cmd as python
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#339 Update the cmd as python in all solver images
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#341 Name Conversion of ubi to rhel 8.0
  openshift/buildConfig-template.yaml
  openshift/job-template.yaml
Labels: approved, size/S

#344 Correctly report issues when aggregating metadata for old packages
  thoth/solver/python/python.py
Labels: approved, size/S

#345 Updated Imagestream from ubi to rhel
  openshift/imageStream-template.yaml
Labels: approved, size/XS

#347 Dot not allowed in container name as per DNS-1123
  openshift/job-template.yaml
Labels: approved, size/XS

#348 Fixing metadata part, missed previously
  openshift/job-template.yaml
Labels: approved, size/XS

#349 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#346 Install py3.6 as base python in f29
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#351 updated templates with annotations and param thoth-advise-value
  .zuul.yaml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
Labels: approved, size/S
