Repository thoth-station/solver, pull requests merged in 2019-06, with the labels that each got.

#230 Check if the given package in the given version was solved by specific solver
  thoth/solver/python/python.py
Labels: approved, size/S

#232 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#233 Automatic update of dependency pip-tools from 3.7.0 to 3.8.0
  Pipfile.lock
Labels: bot

#231 Solver is a standalone container, not sidecar
  openshift/job-template.yaml
Labels: approved, size/S

#234 Automatic update of dependency virtualenv from 16.6.0 to 16.6.1
  Pipfile.lock
Labels: bot

#235 Add build trigger with generic webhook
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#236 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#240 Release of version 1.2.0
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: bot, size/M

#239 Configure pod ttl to be same as job ttl
  openshift/job-template.yaml
Labels: approved, size/XS

#241 Quote package name in case of no releases found
  thoth/solver/python/base.py
Labels: approved, size/XS

#237 Fix permission denied when installing to venv
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#242 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot
