Repository thoth-station/solver, pull requests merged in 2019-07, with the labels that each got.

#244 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#245 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#246 Automatic update of dependency virtualenv from 16.6.1 to 16.6.2
  Pipfile.lock
Labels: bot

#247 Include MANIFEST.in file
  MANIFEST.in
Labels: size/XS

#249 Release of version 1.2.1
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: bot, size/S

#250 Automatic update of dependency pip-tools from 3.8.0 to 3.9.0
  Pipfile.lock
Labels: bot

#251 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#253 Be more precise with the exception raised
  thoth/solver/python/base.py
Labels: approved, size/XS

#255 Release of version 1.2.2
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: bot, size/XS

#256 Automatic update of dependency virtualenv from 16.6.2 to 16.7.0
  Pipfile.lock
Labels: bot

#257 Automatic update of dependency thoth-python from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#258 Automatic update of dependency thoth-common from 0.9.4 to 0.9.5
  Pipfile.lock
Labels: bot

#260 Automatic update of dependency virtualenv from 16.7.0 to 16.7.1
  Pipfile.lock
Labels: bot

#261 Automatic update of dependency pip-tools from 3.9.0 to 4.0.0
  Pipfile.lock
Labels: bot

#262 Automatic update of dependency virtualenv from 16.7.1 to 16.7.2
  Pipfile.lock
Labels: bot
