Repository thoth-station/solver, pull requests merged in 2019-08, with the labels that each got.

#264 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#265 Automatic update of dependency thoth-python from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot

#266 Automatic update of dependency thoth-common from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#267 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#269 Retry if client gets disconnected
  thoth/solver/python/python.py
Labels: size/S

#271 Be consistent with labels on solvers
  openshift/job-template.yaml
Labels: approved, size/S

#276 Automatic update of dependency virtualenv from 16.7.2 to 16.7.3
  Pipfile.lock
Labels: bot

#274 Do sub-graph checks also on direct dependencies
  thoth/solver/python/python.py
Labels: approved, size/S

#275 Increase memory requests due to OOM in the cluster
  openshift/job-template.yaml
Labels: approved, size/XS

#277 Correctly propagate fetcher kwargs
  thoth/solver/python/base.py
Labels: approved, size/XS, size/XXL

#279 Perform backoff and fix connection only errors
  thoth/solver/python/python.py
Labels: approved, size/S

#281 Check if the given package is provided by index
  thoth/solver/python/python.py
Labels: approved, size/XS

#282 Automatic update of dependency virtualenv from 16.7.3 to 16.7.4
  Pipfile.lock
Labels: bot

#283 Automatic update of dependency pip-tools from 4.0.0 to 4.1.0
  Pipfile.lock
Labels: bot
