Repository thoth-station/solver, pull requests merged in 2020-01, with the labels that each got.

#419 Use arbitrary equality for solvers
  thoth/solver/python/python.py
Labels: approved, size/XS

#423 Increase memory requirements for solvers
  openshift/all-jobs-template.yaml
  openshift/job-template.yaml
Labels: approved, size/M

#422 Decrease liveness probe to avoid long-living jobs
  openshift/all-jobs-template.yaml
  openshift/job-template.yaml
Labels: approved, size/M

#425 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/L

#421 Happy new year!
  docs/source/conf.py
  tests/base.py
  tests/python/test_instrument.py
  tests/python/test_python.py
  tests/python/test_python_solver.py
  thoth/solver/__init__.py
  thoth/solver/cli.py
  thoth/solver/exceptions.py
  thoth/solver/python/__init__.py
  thoth/solver/python/base.py
  thoth/solver/python/instrument.py
  thoth/solver/python/python.py
  thoth/solver/python/python_solver.py
Labels: approved, size/S

#426 Automatic update of dependency thoth-python from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/XS

#427 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#429 Format using black, add ignore comments for dict specific types
  thoth/solver/python/python.py
Labels: approved, size/S

#424 Automatic update of dependency packaging from 19.2 to 20.0
  Pipfile.lock
Labels: bot, size/S

#430 Automatic update of dependency thoth-python from 0.8.0 to 0.9.0
  Pipfile.lock
Labels: bot, size/XS

#428 Move package parsing logic to thoth-python
  mypy.ini
  thoth/solver/python/python.py
Labels: approved, size/M

#432 Release of version 1.5.0
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: bot, size/M

#433 Automatic update of dependency thoth-python from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot, size/XS

#434 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/S

#435 Automatic update of dependency importlib-metadata from 1.3.0 to 1.4.0
  Pipfile.lock
Labels: bot, size/S

#436 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/L

#437 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/M

#438 Automatic update of dependency thoth-analyzer from 0.1.7 to 0.1.8
  Pipfile.lock
Labels: bot, size/M

#439 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/XS

#440 Add standard template for solver workflows
  openshift/solve_and_sync-template.yaml
  workflows/templates/solver-template.yaml
  workflows/templates/sync-template.yaml
Labels: approved, size/L

#441 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#443 Standardize solver name variable
  openshift/solve_and_sync-template.yaml
  workflows/templates/solver-template.yaml
Labels: approved, size/S

#444 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/XS

#442 Rename solver-rhel-8.0 to solver-rhel-8
  openshift/all-jobs-template.yaml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
  openshift/solve_and_sync-template.yaml
Labels: approved, size/M

#445 Update template name
  openshift/job-template.yaml
Labels: approved, size/XS

#446 Automatic update of dependency autopep8 from 1.4.4 to 1.5
  Pipfile.lock
Labels: bot, size/S

#447 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/XS

#448 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#449 Automatic update of dependency packaging from 20.0 to 20.1
  Pipfile.lock
Labels: bot, size/M

#450 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#451 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#452 Adjust parameters in solver workflow
  openshift/solve_and_sync-template.yaml
  workflows/templates/solver-template.yaml
  workflows/templates/sync-template.yaml
Labels: approved, size/L

#453 Automatic update of dependency importlib-metadata from 1.4.0 to 1.5.0
  Pipfile.lock
Labels: bot, size/S

#454 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/XS

#455 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/M

#456 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
