Repository thoth-station/solver, pull requests merged in 2020-09, with the labels that each got.

#608 Do not use environment marker for importlib-metadata
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/L

#615 Release of version 1.6.1
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: approved, bot, size/S

#616 Add version in log by default
  thoth/solver/cli.py
  thoth/solver/python/python.py
Labels: approved, size/XS

#619 Release of version 1.6.2
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: approved, bot, size/XS

#621 Automatic update of dependency thoth-common from 0.17.3 to 0.18.3
  Pipfile.lock
Labels: approved, bot, size/L

#622 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/S

#623 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/S
