Repository thoth-station/solver, pull requests merged in 2020-07, with the labels that each got.

#575 Fixed precommit errors
  .gitignore
  docs/source/conf.py
  setup.py
  tests/__init__.py
  tests/base_test.py
  tests/python/__init__.py
  tests/python/instrument_test.py
  tests/python/python_solver_test.py
  tests/python/python_test.py
Labels: approved, size/S

#576 Automatic update of dependency thoth-common from 0.13.12 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/M

#567 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: approved, bot, size/XS

#577 Remove templates that are handled by thoth-application
  openshift/all-jobs-template.yaml
  openshift/buildConfig-template.yaml
  openshift/fedora-imagestreamtags.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
  openshift/solve_and_sync-template.yaml
  workflows/templates/solver-template.yaml
Labels: approved, size/XXL

#578 Automatic update of dependency virtualenv from 20.0.25 to 20.0.26
  Pipfile.lock
Labels: approved, bot, size/S

#574 Automatic update of dependency mypy from 0.781 to 0.782
  Pipfile.lock
Labels: bot, size/M

#585 Add environment marker for importlib-metadata
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/M

#588 Make thoth-solver work with Python 3.8+
  thoth/solver/python/instrument.py
Labels: size/S

#594 Fix mypy errors for duplicate imports
  thoth/solver/python/instrument.py
Labels: approved, size/S

#591 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/L

#592 Automatic update of dependency pytest from 5.4.3 to 6.0.0
  Pipfile.lock
Labels: approved, bot, size/L

#595 Automatic update of dependency virtualenv from 20.0.27 to 20.0.28
  Pipfile.lock
Labels: approved, bot, size/S

#596 Automatic update of dependency pytest from 5.4.3 to 6.0.1
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/XS

#597 thoth solver dockerfiles
  dockerfile/Dockerfile.solver-fedora-28-py36
  dockerfile/Dockerfile.solver-fedora-29-py36
  dockerfile/Dockerfile.solver-fedora-29-py37
  dockerfile/Dockerfile.solver-fedora-30-py36
  dockerfile/Dockerfile.solver-fedora-30-py37
  dockerfile/Dockerfile.solver-fedora-31-py36
  dockerfile/Dockerfile.solver-fedora-31-py37
  dockerfile/Dockerfile.solver-fedora-31-py38
  dockerfile/Dockerfile.solver-fedora-32-py37
  dockerfile/Dockerfile.solver-fedora-32-py38
  dockerfile/Dockerfile.solver-rhel-8-py36
  dockerfile/Dockerfile.solver-rhel-8.1-py36
Labels: approved, size/L

#598 support solver image build with ci pipeline
  .aicoe-ci.yaml
  pipeline.yaml
Labels: size/L

#600 Release of version 1.6.0
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: approved, bot, size/M

#602 Automatic update of dependency virtualenv from 20.0.28 to 20.0.29
  Pipfile.lock
Labels: approved, bot, size/S
