Repository thoth-station/solver, pull requests merged in 2020-05, with the labels that each got.

#545 added Fedora32 Python 3.8 and 3.7 solver buildconfigs
  .gitignore
  .pre-commit-config.yaml
  MANIFEST.in
  Pipfile.lock
  README.rst
  docs/source/conf.py
  mypy.ini
  openshift/all-jobs-template.yaml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
  openshift/solve_and_sync-template.yaml
  pyproject.toml
  tests/data/metadata/tensorflow.json
  tests/python/test_python.py
  tests/python/test_python_solver.py
  thoth/solver/cli.py
  thoth/solver/python/base.py
  thoth/solver/python/instrument.py
  thoth/solver/python/python.py
Labels: approved, size/L

#546 Automatic update of dependency packaging from 20.3 to 20.4
  Pipfile.lock
Labels: bot, size/S

#547 Automatic update of dependency virtualenv from 20.0.20 to 20.0.21
  Pipfile.lock
Labels: bot, size/M

#548 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/XS

#528 Add workflow timeout
  openshift/solve_and_sync-template.yaml
Labels: approved, size/XS

#549 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/S

#550 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#551 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/XS

#552 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/XS

#553 introduce logic for Podgc and workflows life
  openshift/solve_and_sync-template.yaml
Labels: approved, size/S

#554 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/S

#555 Automatic update of dependency autopep8 from 1.5.2 to 1.5.3
  Pipfile.lock
Labels: bot, size/XS
