Repository thoth-station/solver, pull requests merged in 2020-06, with the labels that each got.

#557 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/S

#558 Automatic update of dependency mypy from 0.770 to 0.780
  Pipfile.lock
Labels: bot, size/M

#559 Automatic update of dependency importlib-metadata from 1.6.0 to 1.6.1
  Pipfile.lock
Labels: bot, size/S

#560 Keep workflows for SLI
  openshift/solve_and_sync-template.yaml
Labels: approved, size/XS

#566 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.1
  Pipfile.lock
Labels: bot, size/M

#562 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: bot, size/XS

#561 Automatic update of dependency pipdeptree from 0.13.2 to 1.0.0
  Pipfile.lock
Labels: bot, size/XS

#563 Automatic update of dependency thoth-common from 0.13.8 to 0.13.12
  Pipfile.lock
Labels: bot, size/XS

#564 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: bot, size/XS

#570 Automatic update of dependency virtualenv from 20.0.21 to 20.0.24
  Pipfile.lock
Labels: approved, bot

#569 Automatic update of dependency mypy from 0.780 to 0.781
  Pipfile.lock
Labels: approved, bot

#571 Automatic update of dependency importlib-metadata from 1.6.1 to 1.7.0
  Pipfile.lock
Labels: approved, bot

#573 Automatic update of dependency virtualenv from 20.0.24 to 20.0.25
  Pipfile.lock
Labels: bot
