Repository thoth-station/solver, pull requests merged in 2020-03, with the labels that each got.

#478 Adjust template for solvers
  Pipfile
  Pipfile.lock
  openshift/solve_and_sync-template.yaml
  workflows/templates/solver-template.yaml
Labels: do-not-merge/work-in-progress, size/L

#501 Fix detection of libraries that are shared with thoth-solver itself
  thoth/solver/python/instrument.py
Labels: approved, size/M

#503 Automatic update of dependency importlib-metadata from 1.5.0 to 1.6.0
  Pipfile.lock
Labels: bot, size/L

#508 Release of version 1.5.1
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: bot, size/M

#506 Automatic update of dependency pytest from 5.4.0 to 5.4.1
  Pipfile.lock
Labels: bot, size/XS

#505 Automatic update of dependency virtualenv from 20.0.10 to 20.0.15
  Pipfile.lock
Labels: bot, size/S

#504 Automatic update of dependency thoth-common from 0.10.11 to 0.12.4
  Pipfile.lock
Labels: bot, size/S

#507 Automatic update of dependency pytest-mypy from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot, size/XS

#511 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/M
