Repository thoth-station/solver, pull requests merged in 2020-11, with the labels that each got.

#639 solver based on ubi8 and python38
  dockerfile/Dockerfile.solver-rhel-8-py38
  pipeline.yaml
Labels: approved, size/M

#643 Automatic update of dependency pytest-mypy from 0.7.0 to 0.8.0
  Pipfile.lock
Labels: approved, bot, size/L

#642 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#641 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/L

#640 Automatic update of dependency requests from 2.24.0 to 2.25.0
  Pipfile.lock
Labels: approved, bot, size/L

#648 Release of version 1.6.3
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: approved, bot, size/M

#650 port to python 38
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#651 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS
