Repository thoth-station/solver, pull requests merged in 2020-04, with the labels that each got.

#512 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#510 Remove hack/ as it is no longer needed
  hack/Dockerfile.fc26
  hack/Dockerfile.fc27
  hack/build.sh
Labels: approved, size/M

#513 More resources for bigger stacks
  workflows/templates/solver-template.yaml
Labels: approved, size/XS

#514 Use RHEL 8
  .thoth.yaml
Labels: approved

#515 Automatic update of dependency virtualenv from 20.0.15 to 20.0.16
  Pipfile.lock
Labels: bot, size/M

#516 Automatic update of dependency pytest-mypy from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot, size/XS

#518 Setup workflow TTL strategy to reduce preassure causing OOM
  openshift/solve_and_sync-template.yaml
Labels: approved, size/XS

#519 Automatic update of dependency autopep8 from 1.5 to 1.5.1
  Pipfile.lock
Labels: bot, size/S

#517 Fix when no output was produced and JSON flag was set to true
  thoth/solver/python/instrument.py
Labels: approved, size/XS

#520 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/XS

#521 Give solver 30 minutes to compute results
  workflows/templates/solver-template.yaml
Labels: approved, size/XS

#522 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#524 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/XS

#523 consistency in workflow while using secrets
  workflows/templates/solver-template.yaml
Labels: approved, size/XS

#525 Automatic update of dependency virtualenv from 20.0.16 to 20.0.17
  Pipfile.lock
Labels: bot, size/S

#527 Automatic update of dependency virtualenv from 20.0.17 to 20.0.18
  Pipfile.lock
Labels: bot, size/M

#530 Automatic update of dependency thoth-python from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot, size/XS

#529 Automatic update of dependency autopep8 from 1.5.1 to 1.5.2
  Pipfile.lock
Labels: bot, size/XS

#532 Release of version 1.5.2
  CHANGELOG.md
  thoth/solver/__init__.py
Labels: bot, size/S

#533 Propagate information about platform from solver run
  thoth/solver/python/python.py
Labels: approved, size/XS

#534 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#536 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#537 Automatic update of dependency pytest-mypy from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot, size/XS

#539 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/S

#540 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/XS

#541 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
