Repository thoth-station/solver, pull requests merged in 2020-02, with the labels that each got.

#457 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#459 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#460 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#461 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/S

#458 Adjust name and volume in templates
  openshift/job-template.yaml
  openshift/solve_and_sync-template.yaml
Labels: approved, size/XS

#464 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#467 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/M

#469 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#471 Use solver-workload-operator name for stage solver jobs
  openshift/all-jobs-template.yaml
Labels: approved, size/L

#472 Automatic update of dependency requests from 2.22.0 to 2.23.0
  Pipfile.lock
Labels: bot, size/M

#474 Automatic update of dependency pytest-mypy from 0.4.2 to 0.5.0
  Pipfile.lock
Labels: bot, size/M

#475 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/XS

#479 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
