Repository thoth-station/solver, pull requests merged in 2021-03, with the labels that each got.

#678 Execute solvers with app script to call solver python cli
  app.py
  app.sh
Labels: approved, size/XS

#679 Fix CI failures
  Pipfile.lock
  tests/python/instrument_test.py
  thoth/solver/python/instrument.py
Labels: do-not-merge/hold, size/L

#686 Skip thoth-solver in the environment packages report
  thoth/solver/python/python.py
Labels: approved, lgtm, size/XS

#681 minor CI related updates
  .aicoe-ci.yaml
  .coafile
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .pre-commit-config.yaml
  .prow.yaml
Labels: kind/demo, sig/devops, size/M
