Repository thoth-station/solver, pull requests merged in 2021-02, with the labels that each got.

#662 Add bits needed for s2i integration
  .s2i/bin/assemble
  .thoth.yaml
  app.py
  dockerfile/Dockerfile.solver-fedora-28-py36
  dockerfile/Dockerfile.solver-fedora-29-py36
  dockerfile/Dockerfile.solver-fedora-29-py37
  dockerfile/Dockerfile.solver-fedora-30-py36
  dockerfile/Dockerfile.solver-fedora-30-py37
  dockerfile/Dockerfile.solver-fedora-31-py36
  dockerfile/Dockerfile.solver-fedora-31-py37
  dockerfile/Dockerfile.solver-fedora-31-py38
  dockerfile/Dockerfile.solver-fedora-32-py37
  dockerfile/Dockerfile.solver-fedora-32-py38
  dockerfile/Dockerfile.solver-rhel-8-py36
  dockerfile/Dockerfile.solver-rhel-8-py38
  dockerfile/Dockerfile.solver-rhel-8.1-py36
  overlays/solver-fedora-30-py36/Pipfile
  overlays/solver-fedora-30-py36/Pipfile.lock
  overlays/solver-fedora-30-py37/Pipfile
  overlays/solver-fedora-30-py37/Pipfile.lock
  overlays/solver-fedora-31-py36/Pipfile
  overlays/solver-fedora-31-py36/Pipfile.lock
  overlays/solver-fedora-31-py37/Pipfile
  overlays/solver-fedora-31-py37/Pipfile.lock
  overlays/solver-fedora-31-py38/Pipfile
  overlays/solver-fedora-31-py38/Pipfile.lock
  overlays/solver-fedora-32-py37/Pipfile
  overlays/solver-fedora-32-py37/Pipfile.lock
  overlays/solver-fedora-32-py38/Pipfile
  overlays/solver-fedora-32-py38/Pipfile.lock
  overlays/solver-rhel-8-py36/Pipfile
  overlays/solver-rhel-8-py36/Pipfile.lock
  overlays/solver-rhel-8-py38/Pipfile
  overlays/solver-rhel-8-py38/Pipfile.lock
Labels: approved, lgtm, size/XXL

#666 Remove old Fedora S2I images
  .thoth.yaml
Labels: approved, lgtm, size/S

#667 Update README and remove old build section
  README.rst
Labels: approved, lgtm, size/M

#668 Explicitly turn on pre-releases in Python dependency parser
  tests/python/python_solver_test.py
  thoth/solver/python/python_solver.py
Labels: approved, size/S

#672 Run pytest with Python 3.8
  .aicoe-ci.yaml
Labels: size/XS

#673 update aicoe-ci configuration to support overlays build
  .aicoe-ci.yaml
  pipeline.yaml
Labels: size/L
