Repository thoth-station/solver, pull requests merged in 2021-05, with the labels that each got.

#697 Use thoth.solver logger in the CLI setup
  thoth/solver/cli.py
Labels: approved, size/XS

#706 update the prow resource limits
  .prow.yaml
Labels: size/XS

#707 Metadata now gather also description
  tests/data/metadata/click.json
  tests/data/metadata/delegator-py.json
  tests/python/instrument_test.py
  tests/python/python_test.py
  thoth/solver/python/instrument.py
  thoth/solver/python/python.py
Labels: approved, size/L

#701 Compute packages available in analyzed Python package release
  thoth/solver/python/python.py
Labels: approved, do-not-merge/hold, size/S

#704 Raise on exit code propagating a signal from operating system
  thoth/solver/python/python.py
Labels: approved, size/XS

#710 Remove unnecessary whitespace
  thoth/solver/python/python.py
Labels: approved, size/XS
