Repository thoth-station/solver, pull requests merged in 2021-06, with the labels that each got.

#711 Add Fedora 34 based on Python 3.9 solver
  .aicoe-ci.yaml
  .thoth.yaml
  README.rst
Labels: approved, lgtm, size/S

#716 Remove Fedora 31 + Python 3.7 it went EOL
  README.rst
Labels: approved, lgtm, size/S

#722 Adjust copyright notice in headers
  tests/base_test.py
  tests/python/instrument_test.py
  tests/python/python_solver_test.py
  tests/python/python_test.py
  thoth/solver/__init__.py
  thoth/solver/cli.py
  thoth/solver/exceptions.py
  thoth/solver/python/__init__.py
  thoth/solver/python/base.py
  thoth/solver/python/instrument.py
  thoth/solver/python/python.py
  thoth/solver/python/python_solver.py
Labels: approved, size/S

#723 updates from the template project
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, lgtm, size/S
